<a href="https://colab.research.google.com/github/ywchanna2001/Implementing_AF2_From_Scratch/blob/main/Introduction_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Creation

In [1]:
import torch
torch.tensor([2.0,1.45,-1.0,0.0])

tensor([ 2.0000,  1.4500, -1.0000,  0.0000])

In [ ]:
#shape(5,)
torch.linspace(0,2,steps=5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000])

In [ ]:
#shape(10,)
torch.linspace(0,2,steps=10)

tensor([0.0000, 0.2222, 0.4444, 0.6667, 0.8889, 1.1111, 1.3333, 1.5556, 1.7778,
        2.0000])

In [ ]:
#shape(4,3,5)
torch.ones((4,3,5))*5

tensor([[[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]]])

In [3]:
A = torch.tensor([3,5,1])
B = torch.tensor([4,5,8])
comparison = A < B

print(comparison)

tensor([ True, False,  True])


In [4]:
as_float = comparison.float()
print(as_float)

tensor([1., 0., 1.])


# Axis-Wise Operations

In [6]:
# Shape(4,3)
A = torch.arange(12).reshape(4,3)

In [7]:
# Summing up the rows
A.sum(dim=0)


tensor([18, 22, 26])

In [8]:
# Summing up the columns
A.sum(dim=1)

tensor([ 3, 12, 21, 30])

In [9]:
# Summing up all the elements
A.sum(dim=None)

tensor(66)

In [10]:
torch.argmax(A, dim=1)

tensor([2, 2, 2, 2])

In [12]:
torch.argmax(A, dim=0)

tensor([3, 3, 3])

In [20]:
A = A.float()
torch.mean(A, dim=1)

tensor([ 1.,  4.,  7., 10.])

In [21]:
torch.std(A, dim=1)

tensor([1., 1., 1., 1.])

In [22]:
torch.linalg.vector_norm(A, dim=1)

tensor([ 2.2361,  7.0711, 12.2066, 17.3781])

# Broadcasting

In [24]:
B = torch.tensor([1,2,3])
B

tensor([1, 2, 3])

In [28]:
B = B.reshape(1,3)
C = A+B

In [29]:
C

tensor([[ 1.,  3.,  5.],
        [ 4.,  6.,  8.],
        [ 7.,  9., 11.],
        [10., 12., 14.]])

In [30]:
B

tensor([[1, 2, 3]])

In [4]:
i = 2
k = 3
j = 2

A = torch.randn(i, k)
B = torch.randn(k, j)

C = A.reshape(i, k, 1) * B.reshape(1, k, j)

In [5]:
A

tensor([[-1.1548, -0.2998, -0.4625],
        [ 0.2264, -0.6319,  0.8441]])

In [6]:
B

tensor([[-1.2136, -0.9850],
        [ 1.6394,  0.2045],
        [-0.0953,  0.5868]])

In [7]:
C

tensor([[[ 1.4015,  1.1375],
         [-0.4915, -0.0613],
         [ 0.0441, -0.2714]],

        [[-0.2748, -0.2230],
         [-1.0359, -0.1292],
         [-0.0804,  0.4953]]])